# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
      time: "14:00"
    assignees:
      - "onissen"
    commit-message:
      prefix: "[dependabot/root]"
      prefix-development: "[dependabot/root] devDependency"
      include: "scope"
    labels:
      - "dependencies"
    groups:
      patch-updates:
        update-types: 
        - "patch"
      dev-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/cockpit-api"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
    assignees:
      - "onissen"

    ignore:
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-router-dom"
      - dependency-name: "styled-components"
      # Those dependencies are used by the Strapi Admin Panel. Updating them automatically will end in broken Strapi Admin.
    
    groups:
      strapi:
        patterns:
        - "@strapi*"
        - "strapi*"
      patch-updates:
        update-types: 
        - "patch"
      dev-dependencies:
        dependency-type: "development"
    commit-message:
      prefix: "[dependabot/api]"
      prefix-development: "[dependabot/api] devDependency"
      include: "scope"
    labels:
      - "dependencies"

  - package-ecosystem: npm
    directory: "/cockpit-frontend"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "14:00"
    assignees:
      - "onissen"
    commit-message:
      prefix: "[dependabot/frontend]"
      prefix-development: "[dependabot/frontend] devDependency"
      include: "scope"
    labels:
      - "dependencies"
