name: Neues Feature
description: Schlage ein neues Feature vor
labels: ["enhancement"]
title: "[Add]: "

body:
    - type: textarea
    attributes:
        label: Was ist der Plan?
        placeholder: Beschreibe das gewünschte neue Feature
    validation:
        required: true

    - type: textarea
    attributes:
        label: Weitere Beschreibungen
        placeholder: Gibt es noch etwas zu sagen?

    - type: markdown
    attributes:
        value: "## Issue Einstellungen"
    - type: markdown
    attributes:
    value: | 
        Bitte nimm noch folgende Einstellungen vor:
        - Vergebe das Label `general` wenn es sich um einen Issue handelt, der sich auf die ganze Northware Suite auswirkt.
        - Vergebe das Label `cockpit` wenn es sich um einen Issue handelt, der nur Northware Cockpit betrifft.
        - Ordne diesen Issue einem Northware Projekt zu.
        - Ordne den Issue ggf. einem Milestone zu.
